@startuml

title __MODEL's Class Diagram__\n

  namespace co.siarhei.apps.android.geochat {
    namespace Model {
      class co.siarhei.apps.android.geochat.Model.Chat {
          ~ s : Date
          + Chat()
          + getS()
          + setS()
      }
    }
  }
  

  namespace co.siarhei.apps.android.geochat {
    namespace Model {
      class co.siarhei.apps.android.geochat.Model.Message {
          + contents : String
          + created_at : Date
          + is_anonymaus : boolean
          + origin_lat : double
          + origin_long : double
          + sender : String
          + updated_at : Date
          - id : int
          - message_type : String
          - user_id : String
          + Message()
          + Message()
          + getContents()
          + getId()
          + getIs_anonymaus()
          + getMessage_type()
          + getOrigin_lat()
          + getOrigin_long()
          + getSender()
          + getUser_id()
          + setContents()
          + setId()
          + setIs_anonymaus()
          + setMessage_type()
          + setOrigin_lat()
          + setOrigin_long()
          + setSender()
          + setUser_id()
      }
    }
  }
  

  namespace co.siarhei.apps.android.geochat {
    namespace Model {
      class co.siarhei.apps.android.geochat.Model.PersonalMessage {
          + created_at : Date
          + to_id : String
          + updated_at : Date
          - contents : String
          - from_id : String
          + PersonalMessage()
          + PersonalMessage()
          + getContents()
          + getCreated_at()
          + getFrom_id()
          + getUpdated_at()
          + isTo_id()
          + setContents()
          + setCreated_at()
          + setFrom_id()
          + setTo_id()
          + setUpdated_at()
      }
    }
  }
  

  namespace co.siarhei.apps.android.geochat {
    namespace Model {
      class co.siarhei.apps.android.geochat.Model.User {
          + email_address : String
          + first_name : String
          + last_name : String
          ~ created_at : Date
          ~ fireID : String
          ~ id : int
          ~ updated_at : Date
          + User()
          + User()
          + getCreated_at()
          + getEmail_address()
          + getFireID()
          + getFirst_name()
          + getId()
          + getLast_name()
          + getLocation()
          + getUpdated_at()
          + setCreated_at()
          + setEmail_address()
          + setFireID()
          + setFirst_name()
          + setId()
          + setLast_name()
          + setLocation()
          + setUpdated_at()
      }
    }
  }
  

  co.siarhei.apps.android.geochat.Model.User o-- co.siarhei.apps.android.geochat.Location.UserLocation : location


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
